#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Sep 02, 2021 08:59:53 AM +0530  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m62" -background #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 705x487+731+179
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4644 1274
    wm minsize $top 117 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Downloader by ZeaCeR"
    vTcl:DefineAlias "$top" "MainWindowHome" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab45 \
        -activebackground #ffffff -activeforeground #fd0006 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Snap ITC} -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ff2227 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Downloader 
    vTcl:DefineAlias "$top.lab45" "Topic" vTcl:WidgetProc "MainWindowHome" 1
    entry $top.ent46 \
        -background #eeeeee -disabledforeground #a3a3a3 \
        -font {-family {Courier New} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 444 
    vTcl:DefineAlias "$top.ent46" "urlhere" vTcl:WidgetProc "MainWindowHome" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #1abe07 -disabledforeground #4646ff \
        -font {-family {Yu Gothic UI Semilight} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground #d2dcdf \
        -highlightcolor #000000 -pady 0 -text {+ Paste} 
    vTcl:DefineAlias "$top.but47" "btnpaste" vTcl:WidgetProc "MainWindowHome" 1
    button $top.but48 \
        -activebackground #f00006 -activeforeground #000000 \
        -background #1681c0 -disabledforeground #a3a3a3 \
        -font {-family {Showcard Gothic} -size 18 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text {⬇ Download} 
    vTcl:DefineAlias "$top.but48" "btndownload" vTcl:WidgetProc "MainWindowHome" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff5155 -disabledforeground #a3a3a3 \
        -font {-family {Showcard Gothic} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text X 
    vTcl:DefineAlias "$top.but49" "Button1" vTcl:WidgetProc "MainWindowHome" 1
    label $top.lab46 \
        -activebackground #ffffff -activeforeground #fd0006 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ff2227 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Link 
    vTcl:DefineAlias "$top.lab46" "Topic_1" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 1080p 
    vTcl:DefineAlias "$top.rad52" "p1080" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 720p 
    vTcl:DefineAlias "$top.rad53" "p720" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 480p 
    vTcl:DefineAlias "$top.rad54" "p480" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 360p 
    vTcl:DefineAlias "$top.rad55" "p360" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 240p 
    vTcl:DefineAlias "$top.rad56" "p240" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 144p 
    vTcl:DefineAlias "$top.rad57" "p144" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 64kbps 
    vTcl:DefineAlias "$top.rad58" "f64kbps" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 32kbps 
    vTcl:DefineAlias "$top.rad60" "f32kbps" vTcl:WidgetProc "MainWindowHome" 1
    ttk::separator $top.tSe61 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe61" "TSeparator1" vTcl:WidgetProc "MainWindowHome" 1
    menu $top.m62 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $top.m62 add cascade \
        -menu "$top.m62.men65" -command {{}} -label File 
    set site_3_0 $top.m62
    menu $site_3_0.men65 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $site_3_0.men65 add command \
        -command {#} -label {Paste URL} 
    $site_3_0.men65 add command \
        -command {#} -label Exit 
    $top.m62 add separator \
        
    $top.m62 add cascade \
        -menu "$top.m62.men71" -command {{}} -label Others 
    set site_3_0 $top.m62
    menu $site_3_0.men71 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $site_3_0.men71 add command \
        -command {#} -label Credits 
    ttk::separator $top.tSe63 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe63" "TSeparator1_1" vTcl:WidgetProc "MainWindowHome" 1
    label $top.lab75 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Downloader by ZeaCeR#5641 - v0.3} 
    vTcl:DefineAlias "$top.lab75" "Lcreditsbottom" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 1440p 
    vTcl:DefineAlias "$top.rad45" "p1080_1" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 2160p 
    vTcl:DefineAlias "$top.rad46" "p1080_1_1" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 128kbps 
    vTcl:DefineAlias "$top.rad47" "f128kbps" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 160kbps 
    vTcl:DefineAlias "$top.rad48" "f160kbps" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 192kbps 
    vTcl:DefineAlias "$top.rad49" "f192kbps" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 256kbps 
    vTcl:DefineAlias "$top.rad50" "f256kbps" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text 320kbps 
    vTcl:DefineAlias "$top.rad51" "f320kbps" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Playlist 
    vTcl:DefineAlias "$top.rad59" "p1080_1_1_1" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Video 
    vTcl:DefineAlias "$top.rad61" "p1080_1_1_1_1" vTcl:WidgetProc "MainWindowHome" 1
    radiobutton $top.rad62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semilight} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Channel 
    vTcl:DefineAlias "$top.rad62" "p1080_1_1_1_1_1" vTcl:WidgetProc "MainWindowHome" 1
    ttk::separator $top.tSe46 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe46" "TSeparator2" vTcl:WidgetProc "MainWindowHome" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx -0.014 -y 0 -rely 0.02 -width 0 -relwidth 1.023 \
        -height 0 -relheight 0.134 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.256 -width 444 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.681 -y 0 -rely 0.258 -width 147 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.709 -y 0 -rely 0.493 -width 187 -relwidth 0 \
        -height 184 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.894 -y 0 -rely 0.258 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.178 -width 0 -relwidth 0.087 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
    place $top.rad52 \
        -in $top -x 0 -relx 0.057 -y 0 -rely 0.696 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad53 \
        -in $top -x 0 -relx 0.057 -y 0 -rely 0.795 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad54 \
        -in $top -x 0 -relx 0.199 -y 0 -rely 0.497 -width 0 -relwidth 0.122 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad55 \
        -in $top -x 0 -relx 0.199 -y 0 -rely 0.596 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad56 \
        -in $top -x 0 -relx 0.199 -y 0 -rely 0.696 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad57 \
        -in $top -x 0 -relx 0.199 -y 0 -rely 0.795 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad58 \
        -in $top -x 0 -relx 0.525 -y 0 -rely 0.592 -width 0 -relwidth 0.149 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.rad60 \
        -in $top -x 0 -relx 0.525 -y 0 -rely 0.69 -width 0 -relwidth 0.148 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.tSe61 \
        -in $top -x 0 -relx 0.335 -y 0 -rely 0.481 -width 0 -relwidth 0.003 \
        -height 0 -relheight 0.398 -anchor nw -bordermode ignore 
    place $top.tSe63 \
        -in $top -x 0 -relx 0.044 -y 0 -rely 0.477 -width 0 -relwidth 0.003 \
        -height 0 -relheight 0.398 -anchor nw -bordermode ignore 
    place $top.lab75 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.947 -width 0 -relwidth 0.974 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $top.rad45 \
        -in $top -x 0 -relx 0.057 -y 0 -rely 0.596 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad46 \
        -in $top -x 0 -relx 0.057 -y 0 -rely 0.497 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.rad47 \
        -in $top -x 0 -relx 0.525 -y 0 -rely 0.497 -width 0 -relwidth 0.148 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad48 \
        -in $top -x 0 -relx 0.355 -y 0 -rely 0.795 -width 0 -relwidth 0.148 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad49 \
        -in $top -x 0 -relx 0.355 -y 0 -rely 0.696 -width 0 -relwidth 0.148 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.rad50 \
        -in $top -x 0 -relx 0.355 -y 0 -rely 0.596 -width 0 -relwidth 0.148 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.rad51 \
        -in $top -x 0 -relx 0.355 -y 0 -rely 0.497 -width 0 -relwidth 0.148 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.rad59 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.38 -width 0 -relwidth 0.18 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.rad61 \
        -in $top -x 0 -relx 0.255 -y 0 -rely 0.38 -width 0 -relwidth 0.18 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.rad62 \
        -in $top -x 0 -relx 0.482 -y 0 -rely 0.38 -width 0 -relwidth 0.18 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.tSe46 \
        -in $top -x 0 -relx 0.681 -y 0 -rely 0.477 -width 0 -relwidth 0.003 \
        -height 0 -relheight 0.4 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

