#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Aug 31, 2021 12:08:41 PM +0530  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background #ffffff 
    wm focusmodel $top passive
    wm geometry $top 600x450+781+221
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4644 1274
    wm minsize $top 117 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Credits"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #ffffff -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    label $top.lab47 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font "-family {Showcard Gothic} -size 24 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground #ff0f15 -text Credits 
    vTcl:DefineAlias "$top.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground #ff151c -text {Made by ZeaCeR#5641} 
    vTcl:DefineAlias "$top.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground #41fe6b -activeforeground #000000 \
        -background #ff5559 -disabledforeground #a3a3a3 \
        -font "-family Uniflex_PersonalUseOnly -size 24 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Go back to Home} 
    vTcl:DefineAlias "$top.but50" "Button1" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can54 \
        -background #ffffff -borderwidth 2 -closeenough 1.0 -height 243 \
        -insertbackground black -relief ridge -selectbackground blue \
        -selectforeground white -width 543 
    vTcl:DefineAlias "$top.can54" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.99 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.711 -width 0 -relwidth 0.34 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.8 -width 557 -relwidth 0 \
        -height 74 -relheight 0 -anchor nw -bordermode ignore 
    place $top.can54 \
        -in $top -x 0 -relx 0.3 -y 0 -rely 0.156 -width 0 -relwidth 0.408 \
        -height 0 -relheight 0.544 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

